### 1) Alturas  
i. No trecho de código abaixo, crie um ndarray chamado ```altura_em_centimetros``` transformando a lista ```lista_de_alturas``` em um ndarray do numpy com a função ```np.array()```  
ii. Crie um outro objeto ```altura_em_metros```, com os valores de ```altura_em_centimetros``` convertidos para metros.

In [3]:
import numpy as np


In [9]:
## Criando a lista de centímetros com valores de 170 até 185 con intervalo de 5

lista_de_centimetros = list(range(170, 190, 5))
print(lista_de_centimetros)

[170, 175, 180, 185]


In [19]:
#convertendo a lista para ndarray
altura_em_centimetros = np.array(lista_de_centimetros)
print("Altura em metros:" , altura_em_centimetros)

#convertendo para metros
altura_em_metros = altura_em_centimetros / 100
print("Altura em metros:", altura_em_metros)


Altura em metros: [170 175 180 185]
Altura em metros: [1.7  1.75 1.8  1.85]


### 2) IMC  
i. Considere que pesos em Kg dessas pessoas, na mesma ortem, estão na lista pesos ```lista_pesos = [70, 75, 80, 85]```. Crie um **ndarray** chamado ```pesos``` com a função ```np.array()``` que contenha esses valores.  
ii. Utilizando o objeto que contém as alturas em metros e esse objeto que contém os respectivos pesos em quilos, calcule o IMC desses indivíduos utilizando a aritmética de arrays e guarde os resultados em um objeto chamado ```imc```.

In [60]:
lista_pesos = [70, 75, 80, 85] #criando pesos em kg
pesos = np.array(lista_pesos) #criando np.array
print('Pesos em quilos:', pesos)

#altura em metros baseado no exemplo anterior
altura_em_metros = np.array([1.7, 1.75, 1.8, 1.85])

# Calculando o IMC: IMC = peso / (altura ** 2)
imc = pesos / (altura_em_metros **2)
print('IMC', imc)


Pesos em quilos: [70 75 80 85]
IMC [24.22145329 24.48979592 24.69135802 24.83564646]


### 3) Endividamento

Cálculos de novas variáveis como endividamento total e comprometimento de renda são essenciais para a construção de modelos financeiros em ciência de dados. Áreas não financeiras terão cálculos semelhantes também. Vamos praticar:

Considere que o seguinte ndarray contém os dados de 4 pessoas, total a ser pago a empréstimos mensalmente e renda familiar:

| custo fixo | dívida financeira | renda familiar |
|:----:|:----:|:---|
| 3000  | 1000 | 6000 |
| 2500  | 2500 | 5500 |
| 1000  | 3000 | 7000 |
| 10000 | 5000 | 16000 |

i. Transforme a lista de listas ```dados_financeiros``` no ndarray ```nd_financeiros```.
> ``` dados_financeiros[[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]] ```

ii. Utilize o método ```.transpose ``` e certifique-se de que esse ndarray tenha uma linha por indivíduo e uma coluna por informação. Utilizando a indexação do numpy, imprima no output a segunda linha do array, depois a segunda coluna.

iii. Pratique aritmética com nearrays e calcule o endividamento total como:
$$endividamento\hspace{.2cm}total = \frac{custo \hspace{.2cm}fixo + dívida\hspace{.2cm}financeira}{renda\hspace{.2cm}familiar}$$
Guarde os resultados em uma variável chamada ```endividamento_total``` e verifique os resultados imprimindo o conteúdo dessa variável no output.

iv. Considere que há um erro de digitação que precisa ser corrigido: 3o indivíduo na verdade não possui renda familiar de R\\$7.000,00, mas sim R\\$ 10.000,00. Corrija esse valor e refaça os cálculos.

In [20]:
import numpy as np

dados_financeiros = [[3000, 2500, 1000, 10000],[1000, 2500, 3000, 5000],[6000, 5500, 7000, 16000]]
nd_financeiros = np.array(dados_financeiros)  # Convertendo para array numpy


# Transpondo o array usando .transpose()
nd_financeiros_transposto = nd_financeiros.transpose()

print("Array original:")
print(nd_financeiros)

print("\nArray transposto usando.transpose():")
print(nd_financeiros_transposto)


Array original:
[[ 3000  2500  1000 10000]
 [ 1000  2500  3000  5000]
 [ 6000  5500  7000 16000]]

Array transposto usando.transpose():
[[ 3000  1000  6000]
 [ 2500  2500  5500]
 [ 1000  3000  7000]
 [10000  5000 16000]]


In [62]:
import numpy as np

#Definindo os arrays com os valores dados.
custo_fixo = np.array([3000, 2500, 1000, 10000])           # Custo fixo para cada indivíduo
divida_financeira = np.array([1000, 2500, 3000, 5000])  # Dívida financeira para cada indivíduo
renda_familiar = np.array([6000, 5500, 7000, 16000])       # Renda familiar para cada indivíduo

#calculando endividamento total
endividamento_total = np.round(custo_fixo + divida_financeira / renda_familiar, 2)
print ('Endividamento total (antes da correção):', endividamento_total) 

#corrigindo renda familiar 3º individuo
renda_familiar[2] = 10000

# Refazendo o cálculo com o valor corrigido e arredondando para 2 casas decimais
endividamento_total = np.round(custo_fixo + divida_financeira / renda_familiar, 2)
print("Endividamento total (após a correção):", endividamento_total)


Endividamento total (antes da correção): [ 3000.17  2500.45  1000.43 10000.31]
Endividamento total (após a correção): [ 3000.17  2500.45  1000.3  10000.31]


In [72]:
import numpy as np

#Definindo os arrays com os valores dados.
custo_fixo = np.array([3000, 2500, 1000, 10000])           # Custo fixo para cada indivíduo
divida_financeira = np.array([1000, 2500, 3000, 5000])  # Dívida financeira para cada indivíduo
renda_familiar = np.array([6000, 5500, 7000, 16000])       # Renda familiar para cada indivíduo

#calculando endividamento total



endividamento_total = np.round((custo_fixo + divida_financeira) / renda_familiar * 100, 2)
print ('Endividamento total (antes da correção):', endividamento_total, '%') 

#corrigindo renda familiar 3º individuo
renda_familiar[2] = 10000

# Refazendo o cálculo com o valor corrigido e arredondando para 2 casas decimais e calculando valor percentual
endividamento_total = np.round((custo_fixo + divida_financeira) / renda_familiar * 100, 2)
print("Endividamento total (após a correção):", endividamento_total, '%')


Endividamento total (antes da correção): [66.67 90.91 57.14 93.75] %
Endividamento total (após a correção): [66.67 90.91 40.   93.75] %


### 4) É muito comum precisarmos identificar valores especiais e darmos tratamento a eles quer seja alterando-os quer seja descartando-os. 

O trecho de código abaixo gera um ndarray com números pseudo aleatórios. Considere que para efeitos do estudo que virá, devemos desconsiderar valores iguais a zero. Sendo assim:

i) crie um objeto ```bool_zero``` que traga uma sequencia de booleanos do mesmo tamanho que o objeto poi, e que vale ```True``` quando o valor de ```poi``` é zero, e ```False``` caso contrário.

ii) Conte quantos valores zero existem. Lembre-se de que no final das contas, ```True``` vale 1 para o Python, e ```False``` vale zero, então uma boa dica seria usar a função ```sum()```.

iii) Utilize a indexação booleana que você aprendeu para criar uma variável ```poi_nao_zero``` que aponta para os elementos de ```poi``` diferentes de zero. Dica: você vai pode inverter os elementos do objeto que criou em *ii)* ou escrever a comparação adequada.

In [33]:
import numpy as np

# I objeto poi - obs: o comando np.random.seed(1234) garante que o mesmo resultado será gerado sempre
np.random.seed(1234)

# Gera o array de números pseudo aleatórios seguindo uma distribuição Poisson
poi = np.random.poisson(3, 100)
print(poi)

# Cria o objeto bool_zero, que é True onde o valor de poi é zero, e False caso contrário
bool_zero = (poi==0)

print(bool_zero)

[3 3 6 2 4 5 4 4 2 0 3 3 2 8 2 3 3 3 0 4 4 2 6 6 0 3 4 3 5 2 1 3 2 2 3 2 4
 4 5 7 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 0 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4
 1 1 7 1 2 1 3 7 0 4 4 0 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
[False False False False False False False False False  True False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False  True False False False False False False False False False False
 False False False False]


In [21]:
# II Conta o número de valores zero em poi usando a função sum()
num_zeros = sum(bool_zero)

print(num_zeros)

6


In [43]:
 # III utilize a indexação booleana para criar uma seleção de não-zeros
# dica: inverta o objeto bool_zero

# Cria o objeto bool_zero, que é True onde o valor de poi é zero, e False caso contrário
poi_nao_zero = poi[poi != 0]
print('array', poi_nao_zero)



array [3 3 6 2 4 5 4 4 2 3 3 2 8 2 3 3 3 4 4 2 6 6 3 4 3 5 2 1 3 2 2 3 2 4 4 5 7
 3 5 3 3 2 2 3 6 2 2 4 3 5 2 5 3 2 1 1 4 4 4 6 2 4 1 2 5 5 3 4 1 4 1 1 7 1
 2 1 3 7 4 4 6 1 3 4 2 5 4 5 5 3 4 6 8 2]
